apiVersion: v1
data:
  Dockerfile: |-
    FROM ubuntu:20.04
    RUN \
      apt update && apt install software-properties-common -y && \
      add-apt-repository -y ppa:nginx/stable && \
      apt-get install -y nginx && \
      rm -rf /var/lib/apt/lists/* && \
      echo "\ndaemon off;" >> /etc/nginx/nginx.conf && \
      chown -R www-data:www-data /var/lib/nginx
    VOLUME ["/etc/nginx/sites-enabled", "/etc/nginx/certs", "/etc/nginx/conf.d", "/var/log/nginx", "/var/www/html"]
    WORKDIR /etc/nginx
    CMD ["nginx"]
    EXPOSE 80
    EXPOSE 443
kind: ConfigMap
metadata:
  annotations:
  name: buildcommand
  namespace: default
