apiVersion: v1
data:
  Dockerfile: |-
    FROM ubuntu:20.04
    RUN \
      apt update && apt install nginx -y && \
      rm -rf /var/lib/apt/lists/* && \
      echo "\ndaemon off;" >> /etc/nginx/nginx.conf && \
      chown -R www-data:www-data /var/lib/nginx
    WORKDIR /etc/nginx
    CMD ["nginx"]
    EXPOSE 80
    EXPOSE 443
kind: ConfigMap
metadata:
  annotations:
  name: buildcommand
  namespace: default
